
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS occupation TEXT,
  ADD COLUMN IF NOT EXISTS education TEXT,
  ADD COLUMN IF NOT EXISTS height_cm INTEGER,
  ADD COLUMN IF NOT EXISTS drinking TEXT,
  ADD COLUMN IF NOT EXISTS smoking TEXT,
  ADD COLUMN IF NOT EXISTS has_kids TEXT,
  ADD COLUMN IF NOT EXISTS wants_kids TEXT,
  ADD COLUMN IF NOT EXISTS interests TEXT[] DEFAULT '{}'::text[];
